name: ESLint Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint and Stylistic Plugin
        run: npm install -g eslint @stylistic/eslint-plugin-js

      - name: Run ESLint
        run: |
          npx eslint "**/*.js" --format json --output-file eslint-report.json || true

      - name: Upload ESLint Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.json
          if-no-files-found: ignore
