name: ESLint Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint Globally
        run: npm install -g eslint

      - name: Debug ESLint
        run: npx eslint --debug "**/*.js" || true

      - name: Run ESLint
        run: |
          npx eslint "**/*.js" --format json --output-file eslint-report.json || true

      - name: Check if ESLint report exists
        run: test -f eslint-report.json && echo "ESLint report found." || echo "No ESLint report generated."

      - name: Upload ESLint Report
        if: success() || failure()  # Upload even if ESLint failed
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.json
          if-no-files-found: ignore  # Prevents workflow failure if no report is generated
